# .github/workflows

name: compile
on:
  schedule:
    - cron: '0 2 * * MON'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: Robby-Blue/schul-latex
          path: schul-latex

      - name: Compile
        uses: Robby-Blue/latex-combined-action@v0.1.1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: output.pdf

      - name: Upload to Discord
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: >
          curl $WEBHOOK_URL -X POST -H "Content-Type: multipart/form-data"
          -F 'payload_json={"username": "LaTex"}'
          -F "files[0]=@$GITHUB_WORKSPACE/output.pdf;type=application/pdf"
